data:
  train_bs: 1
  train_width: 512 
  train_height: 512 
  sample_margin: 30  
  sample_rate: 4 
  n_sample_frames: 1
training:
  batch_size: 2
  num_workers: 0
  learning_rate: 1.0e-5
  num_epochs: 2
  use_gpu_video_tensor: True
  video_data_dir: '/home/oem/Downloads/CelebV-HQ/celebvhq/35666'
solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True 
  gradient_checkpointing: False 
  max_train_steps: 30000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1.0e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 200


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

base_model_path: './pretrained_weights/sd-image-variations-diffusers'
vae_model_path: './pretrained_weights/sd-vae-ft-mse'
image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
controlnet_openpose_path: './pretrained_weights/control_v11p_sd15_openpose/diffusion_pytorch_model.bin'

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 


seed: 12580
resume_from_checkpoint: ''
checkpointing_steps: 1000
save_model_epoch_interval: 5
exp_name: 'stage1'
output_dir: './exp_output'  