training:
  batch_size: 4
  num_epochs: 100
  learning_rate: 1e-4
  num_workers: 4
  log_every: 100
  save_every: 10
  checkpoint_dir: "checkpoints/stage1"

data:
  data_dir: "data"
  video_dir: "videos"
  json_file: "metadata.json"
  train_width: 512
  train_height: 512