model:
  frame_dim: 1024
  audio_dim: 768
  num_heads: 8
  temporal_layers: 4
  pretrained_path: "checkpoints/stage1/latest.pt"
  reference_net_path: "checkpoints/stage1/reference_net_latest.pt"

data:
  data_dir: "data"
  video_dir: "videos"
  json_file: "metadata.json"
  train_width: 512
  train_height: 512
  num_frames: 8
  audio_ctx_frames: 2
  sample_rate: 16000

training:
  batch_size: 2
  num_epochs: 100
  learning_rate: 1e-5
  num_workers: 4
  log_every: 100
  save_every: 10
  checkpoint_dir: "checkpoints/stage2"
  device: "cuda"
  mixed_precision: true