model:
  stage2_checkpoint: "checkpoints/stage2/best.pt"
  num_speed_buckets: 9
  embed_dim: 1024
  face_channels: 1
  pretrained_path: "checkpoints/stage2/latest.pt"

data:
  data_dir: "data"
  video_dir: "videos"
  json_file: "metadata.json"
  train_width: 512
  train_height: 512
  num_frames: 8
  audio_ctx_frames: 2
  sample_rate: 16000

training:
  batch_size: 2
  num_epochs: 50
  learning_rate: 1e-5
  num_workers: 4
  log_every: 100
  save_every: 5
  checkpoint_dir: "checkpoints/stage3"
  log_dir: "logs"
  device: "cuda"
  mixed_precision: true
  use_wandb: true
  face_loss_weight: 0.5

evaluation:
  eval_batch_size: 1
  eval_frequency: 1