denoising_unet_config:
  v2:
    act_fn: silu
    attention_head_dim: [5, 10, 20, 20]
    block_out_channels: [320, 640, 1280, 1280]
    center_input_sample: False
    cross_attention_dim: 1024
    down_block_types: ["CrossAttnDownBlock2D", "CrossAttnDownBlock2D", "CrossAttnDownBlock2D", "DownBlock2D"]
    downsample_padding: 1
    dual_cross_attention: False
    flip_sin_to_cos: True
    freq_shift: 0
    in_channels: 4
    layers_per_block: 2
    mid_block_scale_factor: 1
    norm_eps: 1e-05
    norm_num_groups: 32
    num_class_embeds: null
    only_cross_attention: False
    out_channels: 4
    sample_size: 96
    up_block_types: ["UpBlock2D", "CrossAttnUpBlock2D", "CrossAttnUpBlock2D", "CrossAttnUpBlock2D"]
    use_linear_projection: True
    upcast_attention: True
    class_embed_type: null
    resnet_time_scale_shift: default
    projection_class_embeddings_input_dim: null
  default:
    act_fn: silu
    attention_head_dim: 8
    block_out_channels: [320, 640, 1280, 1280]
    center_input_sample: False
    cross_attention_dim: 768
    down_block_types: ["CrossAttnDownBlock2D", "CrossAttnDownBlock2D", "CrossAttnDownBlock2D", "DownBlock2D"]
    downsample_padding: 1
    flip_sin_to_cos: True
    freq_shift: 0
    in_channels: 4
    layers_per_block: 2
    mid_block_scale_factor: 1
    norm_eps: 1e-05
    norm_num_groups: 32
    out_channels: 4
    sample_size: 64
    up_block_types: ["UpBlock2D", "CrossAttnUpBlock2D", "CrossAttnUpBlock2D", "CrossAttnUpBlock2D"]
    only_cross_attention: False
    use_linear_projection: False
    class_embed_type: null
    num_class_embeds: null
    upcast_attention: False
    resnet_time_scale_shift: default
    projection_class_embeddings_input_dim: null



reference_unet_config:
  v2:
    act_fn: silu
    attention_head_dim: [5, 10, 20, 20]
    block_out_channels: [320, 640, 1280, 1280]
    center_input_sample: False
    cross_attention_dim: 1024
    down_block_types: ["CrossAttnDownBlock2D", "CrossAttnDownBlock2D", "CrossAttnDownBlock2D", "DownBlock2D"]
    downsample_padding: 1
    dual_cross_attention: False
    flip_sin_to_cos: True
    freq_shift: 0
    in_channels: 4
    layers_per_block: 2
    mid_block_scale_factor: 1
    norm_eps: 1e-05
    norm_num_groups: 32
    num_class_embeds: null
    only_cross_attention: False
    out_channels: 4
    sample_size: 96
    up_block_types: ["UpBlock2D", "CrossAttnUpBlock2D", "CrossAttnUpBlock2D", "CrossAttnUpBlock2D"]
    use_linear_projection: True
    upcast_attention: True
    class_embed_type: null
    resnet_time_scale_shift: default
    projection_class_embeddings_input_dim: null
  default:
    act_fn: silu
    attention_head_dim: 8
    block_out_channels: [320, 640, 1280, 1280]
    center_input_sample: False
    cross_attention_dim: 768
    down_block_types: ["CrossAttnDownBlock2D", "CrossAttnDownBlock2D", "CrossAttnDownBlock2D", "DownBlock2D"]
    downsample_padding: 1
    flip_sin_to_cos: True
    freq_shift: 0
    in_channels: 4
    layers_per_block: 2
    mid_block_scale_factor: 1
    norm_eps: 1e-05
    norm_num_groups: 32
    out_channels: 4
    sample_size: 64
    up_block_types: ["UpBlock2D", "CrossAttnUpBlock2D", "CrossAttnUpBlock2D", "CrossAttnUpBlock2D"]
    only_cross_attention: False
    use_linear_projection: False
    class_embed_type: null
    num_class_embeds: null
    upcast_attention: False
    resnet_time_scale_shift: default
    projection_class_embeddings_input_dim: null